//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSuiteFrontEnd.AutomationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecutionJob", Namespace="http://schemas.datacontract.org/2004/07/AutomationService.Data")]
    [System.SerializableAttribute()]
    public partial class ExecutionJob : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutomationSuiteFrontEnd.AutomationService.JobDetails DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutomationSuiteFrontEnd.AutomationService.JobFrequency FreqTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutomationSuiteFrontEnd.AutomationService.ExecutionAction[] aoActionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutomationSuiteFrontEnd.AutomationService.ExecutionAction[] aoTriggersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutomationSuiteFrontEnd.AutomationService.ExecutionJobEnvironment oEnvironmentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutomationSuiteFrontEnd.AutomationService.JobDetails Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutomationSuiteFrontEnd.AutomationService.JobFrequency FreqType {
            get {
                return this.FreqTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FreqTypeField, value) != true)) {
                    this.FreqTypeField = value;
                    this.RaisePropertyChanged("FreqType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutomationSuiteFrontEnd.AutomationService.ExecutionAction[] aoActions {
            get {
                return this.aoActionsField;
            }
            set {
                if ((object.ReferenceEquals(this.aoActionsField, value) != true)) {
                    this.aoActionsField = value;
                    this.RaisePropertyChanged("aoActions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutomationSuiteFrontEnd.AutomationService.ExecutionAction[] aoTriggers {
            get {
                return this.aoTriggersField;
            }
            set {
                if ((object.ReferenceEquals(this.aoTriggersField, value) != true)) {
                    this.aoTriggersField = value;
                    this.RaisePropertyChanged("aoTriggers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutomationSuiteFrontEnd.AutomationService.ExecutionJobEnvironment oEnvironment {
            get {
                return this.oEnvironmentField;
            }
            set {
                if ((object.ReferenceEquals(this.oEnvironmentField, value) != true)) {
                    this.oEnvironmentField = value;
                    this.RaisePropertyChanged("oEnvironment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobDetails", Namespace="http://schemas.datacontract.org/2004/07/AutomationService.Data.DynamicDataItem")]
    [System.SerializableAttribute()]
    public partial class JobDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobFrequency", Namespace="http://schemas.datacontract.org/2004/07/AutomationService.Data.Frequency")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AutomationSuiteFrontEnd.AutomationService.JobFrequencyCount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AutomationSuiteFrontEnd.AutomationService.JobFrequencyDate))]
    public partial class JobFrequency : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstScheduledAsStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutomationSuiteFrontEnd.AutomationService.FrequencySetting FrequencyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastRunAsStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastSuccessfulRunAsStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstScheduledAsString {
            get {
                return this.FirstScheduledAsStringField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstScheduledAsStringField, value) != true)) {
                    this.FirstScheduledAsStringField = value;
                    this.RaisePropertyChanged("FirstScheduledAsString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutomationSuiteFrontEnd.AutomationService.FrequencySetting FrequencyType {
            get {
                return this.FrequencyTypeField;
            }
            set {
                if ((this.FrequencyTypeField.Equals(value) != true)) {
                    this.FrequencyTypeField = value;
                    this.RaisePropertyChanged("FrequencyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastRunAsString {
            get {
                return this.LastRunAsStringField;
            }
            set {
                if ((object.ReferenceEquals(this.LastRunAsStringField, value) != true)) {
                    this.LastRunAsStringField = value;
                    this.RaisePropertyChanged("LastRunAsString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastSuccessfulRunAsString {
            get {
                return this.LastSuccessfulRunAsStringField;
            }
            set {
                if ((object.ReferenceEquals(this.LastSuccessfulRunAsStringField, value) != true)) {
                    this.LastSuccessfulRunAsStringField = value;
                    this.RaisePropertyChanged("LastSuccessfulRunAsString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecutionJobEnvironment", Namespace="http://schemas.datacontract.org/2004/07/AutomationService.Data.DynamicDataItem")]
    [System.SerializableAttribute()]
    public partial class ExecutionJobEnvironment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecutionAction", Namespace="http://schemas.datacontract.org/2004/07/AutomationService.Data.Actions")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AutomationSuiteFrontEnd.AutomationService.SQLAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AutomationSuiteFrontEnd.AutomationService.FileAction))]
    public partial class ExecutionAction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobFrequencyCount", Namespace="http://schemas.datacontract.org/2004/07/AutomationService.Data.Frequency")]
    [System.SerializableAttribute()]
    public partial class JobFrequencyCount : AutomationSuiteFrontEnd.AutomationService.JobFrequency {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaximumRunCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaximumRunCount {
            get {
                return this.MaximumRunCountField;
            }
            set {
                if ((this.MaximumRunCountField.Equals(value) != true)) {
                    this.MaximumRunCountField = value;
                    this.RaisePropertyChanged("MaximumRunCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobFrequencyDate", Namespace="http://schemas.datacontract.org/2004/07/AutomationService.Data.Frequency")]
    [System.SerializableAttribute()]
    public partial class JobFrequencyDate : AutomationSuiteFrontEnd.AutomationService.JobFrequency {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastScheduledRunAsStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastScheduledRunAsString {
            get {
                return this.LastScheduledRunAsStringField;
            }
            set {
                if ((object.ReferenceEquals(this.LastScheduledRunAsStringField, value) != true)) {
                    this.LastScheduledRunAsStringField = value;
                    this.RaisePropertyChanged("LastScheduledRunAsString");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FrequencySetting", Namespace="http://schemas.datacontract.org/2004/07/AutomationService.Data.Frequency")]
    public enum FrequencySetting : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fsAdhoc = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fsMonthly = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fsWeekly = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fsDaily = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fsHourly = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fs5Minutes = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fs1Minute = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SQLAction", Namespace="http://schemas.datacontract.org/2004/07/AutomationService.Data.Actions")]
    [System.SerializableAttribute()]
    public partial class SQLAction : AutomationSuiteFrontEnd.AutomationService.ExecutionAction {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutomationSuiteFrontEnd.AutomationService.DatabaseType DatabaseTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutomationSuiteFrontEnd.AutomationService.DatabaseType DatabaseType {
            get {
                return this.DatabaseTypeField;
            }
            set {
                if ((this.DatabaseTypeField.Equals(value) != true)) {
                    this.DatabaseTypeField = value;
                    this.RaisePropertyChanged("DatabaseType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileAction", Namespace="http://schemas.datacontract.org/2004/07/AutomationService.Data.Actions")]
    [System.SerializableAttribute()]
    public partial class FileAction : AutomationSuiteFrontEnd.AutomationService.ExecutionAction {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AutomationSuiteFrontEnd.AutomationService.FileActionType FileTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutomationSuiteFrontEnd.AutomationService.FileActionType FileType {
            get {
                return this.FileTypeField;
            }
            set {
                if ((this.FileTypeField.Equals(value) != true)) {
                    this.FileTypeField = value;
                    this.RaisePropertyChanged("FileType");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatabaseType", Namespace="http://schemas.datacontract.org/2004/07/AutomationService.Data.Actions")]
    public enum DatabaseType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        dbtTeradata = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        dbtNeteeza = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        dbtODBC = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileActionType", Namespace="http://schemas.datacontract.org/2004/07/AutomationService.Data.Actions")]
    public enum FileActionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fatRead = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fatWrite = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fatCreate = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fatDelete = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AutomationService.IWCFInterface")]
    public interface IWCFInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFInterface/GetLog", ReplyAction="http://tempuri.org/IWCFInterface/GetLogResponse")]
        string[] GetLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFInterface/GetLog", ReplyAction="http://tempuri.org/IWCFInterface/GetLogResponse")]
        System.Threading.Tasks.Task<string[]> GetLogAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFInterface/GetJob", ReplyAction="http://tempuri.org/IWCFInterface/GetJobResponse")]
        AutomationSuiteFrontEnd.AutomationService.ExecutionJob GetJob();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFInterface/GetJob", ReplyAction="http://tempuri.org/IWCFInterface/GetJobResponse")]
        System.Threading.Tasks.Task<AutomationSuiteFrontEnd.AutomationService.ExecutionJob> GetJobAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFInterfaceChannel : AutomationSuiteFrontEnd.AutomationService.IWCFInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFInterfaceClient : System.ServiceModel.ClientBase<AutomationSuiteFrontEnd.AutomationService.IWCFInterface>, AutomationSuiteFrontEnd.AutomationService.IWCFInterface {
        
        public WCFInterfaceClient() {
        }
        
        public WCFInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetLog() {
            return base.Channel.GetLog();
        }
        
        public System.Threading.Tasks.Task<string[]> GetLogAsync() {
            return base.Channel.GetLogAsync();
        }
        
        public AutomationSuiteFrontEnd.AutomationService.ExecutionJob GetJob() {
            return base.Channel.GetJob();
        }
        
        public System.Threading.Tasks.Task<AutomationSuiteFrontEnd.AutomationService.ExecutionJob> GetJobAsync() {
            return base.Channel.GetJobAsync();
        }
    }
}
