//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationService.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecutionJob", Namespace="http://schemas.datacontract.org/2004/07/AutomaticFTP.Data")]
    public partial class ExecutionJob : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private AutomaticFTP.Data.Frequency.JobFrequency FreqTypeField;
        
        private string NameField;
        
        private AutomaticFTP.Data.Actions.ExecutionAction[] aoActionsField;
        
        private AutomaticFTP.Data.Actions.ExecutionAction[] aoTriggersField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutomaticFTP.Data.Frequency.JobFrequency FreqType
        {
            get
            {
                return this.FreqTypeField;
            }
            set
            {
                this.FreqTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutomaticFTP.Data.Actions.ExecutionAction[] aoActions
        {
            get
            {
                return this.aoActionsField;
            }
            set
            {
                this.aoActionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutomaticFTP.Data.Actions.ExecutionAction[] aoTriggers
        {
            get
            {
                return this.aoTriggersField;
            }
            set
            {
                this.aoTriggersField = value;
            }
        }
    }
}
namespace AutomaticFTP.Data.Frequency
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobFrequency", Namespace="http://schemas.datacontract.org/2004/07/AutomaticFTP.Data.Frequency")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AutomaticFTP.Data.Frequency.JobFrequencyDate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AutomaticFTP.Data.Frequency.JobFrequencyCount))]
    public partial class JobFrequency : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FirstScheduledAsStringField;
        
        private AutomaticFTP.Data.Frequency.FrequencySetting FrequencyTypeField;
        
        private string LastRunAsStringField;
        
        private string LastSuccessfulRunAsStringField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstScheduledAsString
        {
            get
            {
                return this.FirstScheduledAsStringField;
            }
            set
            {
                this.FirstScheduledAsStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutomaticFTP.Data.Frequency.FrequencySetting FrequencyType
        {
            get
            {
                return this.FrequencyTypeField;
            }
            set
            {
                this.FrequencyTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastRunAsString
        {
            get
            {
                return this.LastRunAsStringField;
            }
            set
            {
                this.LastRunAsStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastSuccessfulRunAsString
        {
            get
            {
                return this.LastSuccessfulRunAsStringField;
            }
            set
            {
                this.LastSuccessfulRunAsStringField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobFrequencyDate", Namespace="http://schemas.datacontract.org/2004/07/AutomaticFTP.Data.Frequency")]
    public partial class JobFrequencyDate : AutomaticFTP.Data.Frequency.JobFrequency
    {
        
        private string LastScheduledRunAsStringField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastScheduledRunAsString
        {
            get
            {
                return this.LastScheduledRunAsStringField;
            }
            set
            {
                this.LastScheduledRunAsStringField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobFrequencyCount", Namespace="http://schemas.datacontract.org/2004/07/AutomaticFTP.Data.Frequency")]
    public partial class JobFrequencyCount : AutomaticFTP.Data.Frequency.JobFrequency
    {
        
        private int MaximumRunCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaximumRunCount
        {
            get
            {
                return this.MaximumRunCountField;
            }
            set
            {
                this.MaximumRunCountField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FrequencySetting", Namespace="http://schemas.datacontract.org/2004/07/AutomaticFTP.Data.Frequency")]
    public enum FrequencySetting : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fsAdhoc = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fsMonthly = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fsWeekly = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fsDaily = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fsHourly = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fs5Minutes = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fs1Minute = 6,
    }
}
namespace AutomaticFTP.Data.Actions
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecutionAction", Namespace="http://schemas.datacontract.org/2004/07/AutomaticFTP.Data.Actions")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AutomaticFTP.Data.Actions.FileAction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AutomaticFTP.Data.Actions.SQLAction))]
    public partial class ExecutionAction : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileAction", Namespace="http://schemas.datacontract.org/2004/07/AutomaticFTP.Data.Actions")]
    public partial class FileAction : AutomaticFTP.Data.Actions.ExecutionAction
    {
        
        private AutomaticFTP.Data.Actions.FileActionType FileTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutomaticFTP.Data.Actions.FileActionType FileType
        {
            get
            {
                return this.FileTypeField;
            }
            set
            {
                this.FileTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SQLAction", Namespace="http://schemas.datacontract.org/2004/07/AutomaticFTP.Data.Actions")]
    public partial class SQLAction : AutomaticFTP.Data.Actions.ExecutionAction
    {
        
        private AutomaticFTP.Data.Actions.DatabaseType DatabaseTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AutomaticFTP.Data.Actions.DatabaseType DatabaseType
        {
            get
            {
                return this.DatabaseTypeField;
            }
            set
            {
                this.DatabaseTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileActionType", Namespace="http://schemas.datacontract.org/2004/07/AutomaticFTP.Data.Actions")]
    public enum FileActionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fatRead = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fatWrite = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fatCreate = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fatDelete = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatabaseType", Namespace="http://schemas.datacontract.org/2004/07/AutomaticFTP.Data.Actions")]
    public enum DatabaseType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        dbtTeradata = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        dbtNeteeza = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        dbtODBC = 2,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWCFInterface")]
public interface IWCFInterface
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFInterface/GetLog", ReplyAction="http://tempuri.org/IWCFInterface/GetLogResponse")]
    string[] GetLog();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFInterface/GetLog", ReplyAction="http://tempuri.org/IWCFInterface/GetLogResponse")]
    System.Threading.Tasks.Task<string[]> GetLogAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFInterface/GetJob", ReplyAction="http://tempuri.org/IWCFInterface/GetJobResponse")]
    AutomaticFTP.Data.ExecutionJob GetJob();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFInterface/GetJob", ReplyAction="http://tempuri.org/IWCFInterface/GetJobResponse")]
    System.Threading.Tasks.Task<AutomaticFTP.Data.ExecutionJob> GetJobAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWCFInterfaceChannel : IWCFInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WCFInterfaceClient : System.ServiceModel.ClientBase<IWCFInterface>, IWCFInterface
{
    
    public WCFInterfaceClient()
    {
    }
    
    public WCFInterfaceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WCFInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WCFInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string[] GetLog()
    {
        return base.Channel.GetLog();
    }
    
    public System.Threading.Tasks.Task<string[]> GetLogAsync()
    {
        return base.Channel.GetLogAsync();
    }
    
    public AutomaticFTP.Data.ExecutionJob GetJob()
    {
        return base.Channel.GetJob();
    }
    
    public System.Threading.Tasks.Task<AutomaticFTP.Data.ExecutionJob> GetJobAsync()
    {
        return base.Channel.GetJobAsync();
    }
}
